name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  BuildResume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            mollenhauer_resume_en_no_picture.tex
            mollenhauer_resume_en_picture.tex
      - name: Move files to compiler_output folder
        run: |
          mkdir compiler_output
          cp ./mollenhauer_resume_en_no_picture.pdf ./compiler_output/mollenhauer_resume_en_no_picture.pdf
          cp ./mollenhauer_resume_en_picture.pdf ./compiler_output/mollenhauer_resume_en_picture.pdf
      - name: Publish PDF and log files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mollenhauer_resume
          path: compiler_output
          if-no-files-found: error
      - name: Generate release tag
        if: github.ref == 'refs/heads/main'
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_${{ github.run_number }}"
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            mollenhauer_resume_en_no_picture.pdf
            mollenhauer_resume_en_picture.pdf
          name: Resume v${{ github.run_number }}
