name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  BuildResume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            mollenhauer_resume.tex
      - name: Move files to compiler_output folder
        run: |
          mkdir compiler_output
          cp ./mollenhauer_resume.pdf ./compiler_output/mollenhauer_resume.pdf
      - name: Publish PDF and log files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mollenhauer_resume
          path: compiler_output
          if-no-files-found: error
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_DATE }}
          files: |
            mollenhauer_resume.pdf
          name: Resume ${{ env.RELEASE_DATE }}
